// Generated by CoffeeScript 1.9.2
(function() {
  var app, express, io, port, redis, redisClient, server;

  express = require('express');

  app = express();

  server = require('http').createServer(app);

  io = require('socket.io')(server);

  redis = require('redis');

  redisClient = redis.createClient();

  port = 8080;

  server.listen(port, function() {
    return console.log('Server listening at port %d', port);
  });

  app.use(express["static"](__dirname + '/public'));

  io.on('connection', function(socket) {
    var addedUser;
    console.log('new connection!');
    addedUser = false;
    socket.on('add user', function(username) {
      socket.username = username;
      addedUser = true;
      socket.emit('login', username);
      return console.log("server: USERNAME ENTERED: " + username);
    });
    return socket.on('new message', function(data) {
      return socket.broadcast.emit('new message', {
        username: socket.username,
        message: data
      });
    });
  });

}).call(this);
